<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CS2_SimpleAdmin.Bench</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.369" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CS2-SimpleAdmin\CS2-SimpleAdmin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MenuManagerApi">
      <HintPath>..\..\CS2-SimpleAdmin\3rd_party\MenuManagerApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
