SET @s = 76561198000012345, @since = NOW() - INTERVAL 90 SECOND, @now = NOW();
SELECT 'Q1 refresh changed bans (updated_at/created window)' AS q;
EXPLAIN SELECT id, player_name, player_steamid, player_ip, status, created, ends, duration FROM sa_bans WHERE (updated_at >= @since OR created >= @since) AND id > 0 ORDER BY id LIMIT 1000;
SELECT 'Q1b same, single server' AS q;
EXPLAIN SELECT id FROM sa_bans WHERE (updated_at >= @since OR created >= @since) AND server_id = 1 AND id > 0 ORDER BY id LIMIT 1000;
SELECT 'Q2 active checksum' AS q;
EXPLAIN SELECT COUNT(*), COALESCE(SUM(id),0) FROM sa_bans WHERE status = 'ACTIVE';
SELECT 'Q2b active checksum single server' AS q;
EXPLAIN SELECT COUNT(*), COALESCE(SUM(id),0) FROM sa_bans WHERE status = 'ACTIVE' AND server_id = 1;
SELECT 'Q3 active page' AS q;
EXPLAIN SELECT id FROM sa_bans WHERE status = 'ACTIVE' AND id > 0 ORDER BY id LIMIT 1000;
SELECT 'Q4 stats (bans)' AS q;
EXPLAIN SELECT COUNT(*) FROM sa_bans WHERE player_steamid = @s;
SELECT 'Q4b stats (warns)' AS q;
EXPLAIN SELECT COUNT(*) FROM sa_warns WHERE player_steamid = @s;
SELECT 'Q5 expire bans' AS q;
EXPLAIN UPDATE sa_bans SET status = 'EXPIRED' WHERE status = 'ACTIVE' AND duration > 0 AND ends <= @now;
SELECT 'Q5b expire mutes (TimeMode 1)' AS q;
EXPLAIN UPDATE sa_mutes SET status = 'EXPIRED' WHERE status = 'ACTIVE' AND duration > 0 AND ends <= @now;
SELECT 'Q5c expire warns' AS q;
EXPLAIN UPDATE sa_warns SET status = 'EXPIRED' WHERE status = 'ACTIVE' AND duration > 0 AND ends <= @now;
SELECT 'Q6 ip keyset page' AS q;
EXPLAIN SELECT steamid, name, address, used_at FROM sa_players_ips WHERE used_at > @since OR (used_at = @since AND (steamid > 0 OR (steamid = 0 AND address > 0))) ORDER BY used_at, steamid, address LIMIT 2000;
SELECT 'Q7 history page' AS q;
EXPLAIN SELECT b.id, 'BAN' AS type, b.created FROM sa_bans b WHERE b.player_steamid = @s UNION ALL SELECT m.id, m.type, m.created FROM sa_mutes m WHERE m.player_steamid = @s UNION ALL SELECT w.id, 'WARN', w.created FROM sa_warns w WHERE w.player_steamid = @s ORDER BY created DESC, type, id DESC LIMIT 50 OFFSET 0;
SELECT 'Q8 ban backfill' AS q;
EXPLAIN UPDATE sa_bans SET player_ip = COALESCE(player_ip, '10.0.0.1') WHERE (player_steamid = @s OR player_ip = '10.0.0.1') AND status = 'ACTIVE' AND (duration = 0 OR ends > @now);
SELECT 'Q9 expire old ip bans' AS q;
EXPLAIN UPDATE sa_bans SET player_ip = NULL WHERE status = 'ACTIVE' AND ends <= @now - INTERVAL 30 DAY;
SELECT 'Q10 delete old player ips' AS q;
EXPLAIN DELETE FROM sa_players_ips WHERE used_at <= @now - INTERVAL 30 DAY;
